_wandb:
    value:
        cli_version: 0.26.1
        e:
            x43zcqssck9erdssdnams9uz9g4r7pwb:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "510924943360"
                        used: "497466753024"
                email: dineshingale2003@gmail.com
                executable: C:\Users\babal\OneDrive\Desktop\Coding\development\new projects\flower-recognition-project\venv\Scripts\python.exe
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 896
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-e87114c6-790b-47b4-26f8-975e942786c2
                host: Dinesh03
                memory:
                    total: "16473231360"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\babal\OneDrive\Desktop\Coding\development\new projects\flower-recognition-project\main.py
                python: CPython 3.12.10
                root: C:\Users\babal\OneDrive\Desktop\Coding\development\new projects\flower-recognition-project
                startedAt: "2026-05-10T12:21:12.647749Z"
                writerId: x43zcqssck9erdssdnams9uz9g4r7pwb
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "2": epoch/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.12.10
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 7
                - 16
                - 38
            "4": 3.12.10
            "5": 0.26.1
            "8":
                - 2
                - 3
            "12": 0.26.1
            "13": windows-amd64
architecture:
    value: CNN-Vanilla
batch_size:
    value: 32
epochs:
    value: 20
learning_rate:
    value: 0.001
